
CREATE TABLE IF NOT EXISTS USERS (
    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40),
    login varchar(40) NOT NULL,
    email varchar(255) NOT NULL,
    birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS FRIENDS (
    user_id integer,
    friend_id integer
);

CREATE TABLE IF NOT EXISTS FILMS (
    film_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL,
    description varchar(200) NOT NULL,
    releaseDate date NOT NULL,
    duration integer NOT NULL,
    rating_mpa_id integer
);

CREATE TABLE IF NOT EXISTS LIKES (
    film_id integer,
    user_id integer
);

CREATE TABLE IF NOT EXISTS GENRES (
    genre_id integer PRIMARY KEY,
    name varchar(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILM_GENRE (
    film_id integer,
    genre_id integer
);

CREATE TABLE IF NOT EXISTS RATING_MPA (
    rating_mpa_id integer PRIMARY KEY,
    name varchar(10) NOT NULL
);
--
--ALTER TABLE "friends" ADD CONSTRAINT "fk_friends_user_id" FOREIGN KEY("user_id")
--REFERENCES "user" ("user_id");
--
--ALTER TABLE "friends" ADD CONSTRAINT "fk_friends_friend_id" FOREIGN KEY("friend_id")
--REFERENCES "user" ("user_id");
--
--ALTER TABLE "films" ADD CONSTRAINT "fk_film_rating_mpa_id" FOREIGN KEY("rating_mpa_id")
--REFERENCES "rating_mpa" ("rating_mpa_id");
--
--ALTER TABLE "likes" ADD CONSTRAINT "fk_likes_film_id" FOREIGN KEY("film_id")
--REFERENCES "films" ("film_id");
--
--ALTER TABLE "likes" ADD CONSTRAINT "fk_likes_user_id" FOREIGN KEY("user_id")
--REFERENCES "users" ("user_id");
--
--ALTER TABLE "film_genre" ADD CONSTRAINT "fk_film_genre_film_id" FOREIGN KEY("film_id")
--REFERENCES "films" ("film_id");
--
--ALTER TABLE "film_genre" ADD CONSTRAINT "fk_film_genre_genre_id" FOREIGN KEY("genre_id")
--REFERENCES "genres" ("genre_id");
--
