CREATE TABLE IF NOT EXISTS USERS (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40),
    login varchar(40) NOT NULL,
    email varchar(255) NOT NULL,
    birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS FRIENDS (
    user_id integer REFERENCES USERS (id),
    friend_id integer REFERENCES USERS (id),
    approved boolean
);

CREATE TABLE IF NOT EXISTS RATING_MPA (
    id integer NOT NULL AUTO_INCREMENT,
    name varchar(10) NOT NULL,
    CONSTRAINT MPA_PK PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS GENRES (
    id integer NOT NULL AUTO_INCREMENT,
    name varchar(20) NOT NULL,
    CONSTRAINT GENRES_PK PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS FILMS (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL,
    description varchar(200) NOT NULL,
    release_date date NOT NULL,
    duration integer NOT NULL,
    rating_mpa_id integer REFERENCES RATING_MPA (id)
);

CREATE TABLE IF NOT EXISTS LIKES (
    film_id integer REFERENCES FILMS (id),
    user_id integer REFERENCES USERS (id)
);

CREATE TABLE IF NOT EXISTS FILM_GENRE (
    film_id integer REFERENCES FILMS (id),
    genre_id integer REFERENCES GENRES (id)
);